-- Este archivo se deja intencionalmente en blanco.
-- Los datos de prueba han sido eliminados para el despliegue en entorno de producción.
-- (El esquema relacional se inicializa mediante schema.sql)
